basic:
    name: 'https://website.pixieset.com'
    environments:
        production: 'https://website.pixieset.com'
        staging: ''
        development: ''
    breakpoints:
        - 640
        - 1024
        - 1200
    pages:
        - /
    monitoring:
        days: {  }
        type: ''
        schedule_time: '12:30 AM'
        schedule_time_zone: Europe/London
        compare_with: last-production
        compare_with_fresh: production
advanced:
    mask: ''
    remove: ''
    isolate: ''
    delay: 15
    scroll: true
    headers:
        - { header: Accept-Language, value: 'en-US,en;q=0.9' }
        - { header: User-Agent, value: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36' }
        - { header: Sec-Fetch-Dest, value: document }
        - { header: Sec-Fetch-Mode, value: navigate }
        - { header: Sec-Fetch-Site, value: same-origin }
        - { header: Sec-Fetch-User, value: '?1' }
        - { header: Upgrade-Insecure-Requests, value: '1' }
        - { header: Connection, value: keep-alive }
        - { header: DNT, value: '1' }
        - { header: Cache-Control, value: max-age=0 }
        - { header: Accept-Encoding, value: 'gzip, deflate, br' }
        - { header: Sec-CH-UA, value: '"Chromium";v="124", "Google Chrome";v="124", "Not-A.Brand";v="99"' }
    cookies: ''
    custom_js: "const allElements = document.querySelectorAll('*');\n  let maxHeight = 0;\n  allElements.forEach((element) => {\n    const elementBottom = element.getBoundingClientRect().bottom + window.scrollY;\n    if (elementBottom > maxHeight) {\n      maxHeight = elementBottom;\n    }\n  });\n  document.documentElement.style.height = `${maxHeight}px`;\n  document.body.style.height = `${maxHeight}px`;"
    custom_css: "\n#body-section-3362487 {\n\tdisplay: block !important;\n\topacity: 1 !important;\n    position: unset !important;\n}\n\nimg, .absolute-fill.js-tint {\n\theight: auto !important;\n}\n\n.theme-4-header__slide.slick-slide {\n\theight: 600px !important;\n    width: 1000px !important;\n}"
    mock_content:
        - { selector: '', type: title }
    login:
        type: custom
        click_element: true
        click_element_selector: .ps-cookie-popup__button.ps-cookie-popup__button--allow
        login_url: '/login/?spId=website'
        username: ''
        password: ''
        username_selector: '[autocomplete="username"]'
        password_selector: '[autocomplete="current-password"]'
        submit_selector: '#login-button'
        after_login_selector: ''
    performance:
        workers_production: 30
        workers_nonproduction: 10
        workers_production_delay: 0
        workers_nonproduction_delay: 0
    stabilize: true
